import pytest


@pytest.mark.django_db
def test_get_sources(api_client):
    raise RuntimeError("Failed test on purpose")